version: '3'

services:
  jjori_py_dev:
    container_name: jjori_py_dev
    image: jjori_py_dev:latest
    build:
      dockerfile: docker/Dockerfile
      context: .
    env_file:
      - .env
    ports:
      - '8000:8000'
#    volumes:
#      - ./frontend:/opt/frontend

networks:
  default:
    external:
      name: jjori